name: Env and Vars Context Demo

on:
  workflow_dispatch:

# Workflow-level environment variable and workflow-level vars
env:
  MY_VAR: workflow-env

vars:
  MY_VAR: workflow-vars

jobs:
  demo-job:
    # Job-level environment variable overrides workflow-level
    env:
      MY_VAR: job-env

    runs-on: ubuntu-latest

    steps:
      - name: Print All Levels
        env:
          MY_VAR: step-env  # Step-level env overrides job-level
        run: |
          echo "Step-level ENV: ${{ env.MY_VAR }}"   # Output: step-env
          echo "Workflow-level VAR: ${{ vars.MY_VAR }}"  # Output: workflow-vars
