name: Simple Env & Vars Demo
on: workflow_dispatch

# 1) Immutable constant (vars)
vars:
  DEFAULT_MESSAGE: "Hello from vars"

# 2) Workflow-level env picks it up
env:
  MESSAGE: ${{ vars.DEFAULT_MESSAGE }}

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show workflow-level MESSAGE
        run: echo "MESSAGE = $MESSAGE"
        # → prints: MESSAGE = Hello from vars

      - name: Override MESSAGE in this step
        env:
          MESSAGE: "Hello from step"
        run: echo "MESSAGE = $MESSAGE"
        # → prints: MESSAGE = Hello from step
