name: Env and Vars Context Demo

on:
  workflow_dispatch:

# ✅ Define both 'env' and 'vars' at the top level of the workflow
env:
  MY_VAR: workflow-env

vars:
  MY_VAR: workflow-vars

jobs:
  demo-job:
    runs-on: ubuntu-latest

    env:
      MY_VAR: job-env  # overrides workflow env

    steps:
      - name: Print ENV and VARS
        env:
          MY_VAR: step-env  # overrides job env
        run: |
          echo "ENV: ${{ env.MY_VAR }}"     # should print 'step-env'
          echo "VARS: ${{ vars.MY_VAR }}"   # should print 'workflow-vars'
