name: Env & Vars Context
on: workflow_dispatch

# 1) Workflow-level ENV — overrides can happen
env:
  GREETING: "Hello from workflow env"

jobs:
  demo:
    runs-on: ubuntu-latest

    # 2) Assign to environment to use 'vars' context (see steps below!)
    environment: demo-env

    # 3) Job-level ENV — overrides workflow-level
    env:
      GREETING: "Hello from job env"

    steps:
      - name: Step 1: Print from env context (no step override)
        run: echo "GREETING from env = $GREETING"
        # Expected: job-level value

      - name: Step 2: Override env at step level
        env:
          GREETING: "Hello from step env"
        run: echo "GREETING from env = $GREETING"
        # Expected: step-level value

      - name: Step 3: Use vars context
        run: |
          echo "GREETING from vars = ${{ vars.GREETING }}"
