name: Env & Vars Context Demo

on:
  workflow_dispatch:

env:
  GREETING: "Hello from workflow env"   # ← Workflow-level ENV

jobs:
  demo:
    runs-on: ubuntu-latest

    environment: demo-env               # ← Link to GitHub Environment

    env:
      GREETING: "Hello from job env"   # ← Job-level override

    steps:
      - name: Step 1: Print from env (job-level)
        run: echo "GREETING from env = $GREETING"

      - name: Step 2: Override env at step level
        env:
          GREETING: "Hello from step env"
        run: echo "GREETING from env = $GREETING"

      - name: Step 3: Print from vars context
        run: echo "GREETING from vars = ${{ vars.GREETING }}"
