# 1) Human‐readable workflow name shown in the Actions tab
name: Env Context

# 2) Trigger: manual dispatch only (Run workflow button)
on:
  workflow_dispatch:

env:
  MY_VAR: workflow       # workflow-level

jobs:
  variables:
    runs-on: ubuntu-latest

    env:                  # job-level override
      MY_VAR: jobs

    steps:
      - name: Print
        env:              # step-level override
          MY_VAR: steps
        run: |
          echo '${{ env.MY_VAR }}'   # → steps
          echo '${{ vars.MY_VAR }}'   # → (would read a vars.MY_VAR constant if defined)
