name: Simple Env Demo
on: workflow_dispatch

# 1) Workflow-level default for EVERY job and step
env:
  MY_VAR: workflow

jobs:
  demo:
    runs-on: ubuntu-latest

    # 2) Job-level override for all steps in this job
    env:
      MY_VAR: job

    steps:
      - name: Show workflow & job value
        run: |
          # No step override, so picks up the job-level "job"
          echo "MY_VAR = $MY_VAR"

      - name: Override in this one step
        env:
          MY_VAR: step
        run: |
          # Step-level always wins
          echo "MY_VAR = $MY_VAR"

      - name: Back to job-level again
        run: |
          # Step has no override, so back to "job"
          echo "MY_VAR = $MY_VAR"
