name: Generate Info
on:
  workflow_call:
    outputs:
      current-time:
        description: 'Current timestamp (UTC)'
      random-number:
        description: 'Random number'

jobs:
  generate:
    runs-on: ubuntu-latest

    # Map step outputs into job outputs
    outputs:
      current-time: ${{ steps.get-time.outputs.time }}
      random-number: ${{ steps.get-random.outputs.number }}

    steps:
      - id: get-time
        run: |
          echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - id: get-random
        run: |
          echo "number=$RANDOM" >> $GITHUB_OUTPUT
