name: Work Flow Demo

on: 
  pull_request:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Build
        run: echo "build started by Shasivadhan"

  test:
    runs-on: windows-latest
    steps:
      - name: Print Test - mozillaaa
        run: echo "test mozillaaa"
      - name: Print test - Safari
        run: echo "test safari"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deploy
        run: echo "deploy"
