name: Work Flow Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      # all Markdown docs
      - '**/*.md'
      # any other YAML “doc” files you use for write-ups
      - '**/*.yml'
      # if you ever add plain-text guides:
      - '**/*.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Build
        run: echo "build"

  test:
    runs-on: windows-latest
    steps:
      - name: Print Test - mozillaaa
        run: echo "test mozillaaa"
      - name: Print test - Safari
        run: echo "test safari"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deploy
        run: echo "deploy"
