name: All Matrix Use Cases

on:
  workflow_dispatch:

jobs:

  # ✅ Use Case 1: Basic OS x Java Version
  basic-matrix:
    name: Basic Matrix: ${{ matrix.os }} - Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 20]
    steps:
      - name: Echo basic combo
        run: echo "OS=${{ matrix.os }}, Java=${{ matrix.java }}"

  # ✅ Use Case 2: Matrix with INCLUDE
  include-matrix:
    name: Include Matrix: ${{ matrix.os }} - Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
          - os: windows-latest
            java: 20
    steps:
      - run: echo "Included pair: ${{ matrix.os }} - ${{ matrix.java }}"

  # ✅ Use Case 3: Matrix with EXCLUDE
  exclude-matrix:
    name: Exclude Matrix: ${{ matrix.os }} - Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 20]
        exclude:
          - os: windows-latest
            java: 20
    steps:
      - run: echo "Allowed pair: ${{ matrix.os }} - ${{ matrix.java }}"

  # ✅ Use Case 4: Matrix with Extra Keys (custom values)
  custom-key-matrix:
    name: Custom Key Matrix: ${{ matrix.os }} - Mode ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            mode: dev
          - os: windows-latest
            java: 20
            mode: prod
    steps:
      - run: echo "Running in ${{ matrix.mode }} mode with Java ${{ matrix.java }} on ${{ matrix.os }}"

  # ✅ Use Case 5: Matrix + fail-fast: false
  failfast-matrix:
    name: Fail-Fast Off Matrix: ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [alpha, beta, prod]
    steps:
      - name: Simulate ${{ matrix.env }}
        run: |
          echo "Running environment: ${{ matrix.env }}"
          if [[ "${{ matrix.env }}" == "beta" ]]; then exit 1; fi
