name: Node Js Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Your Repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # 3. Verify Node Version
      - name: Print Node.js Version
        run: node --version

      # 4. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # 5. Run your tests
      - name: Run tests
        run: npm test
