# File: .github/workflows/main.yml
name: Work Flow Demo

on:
  push:
    branches:
      - main
    tags:
      - 'v*'           # triggers on tags like v1.0, v2.5, etc.
      - 'release-*'    # optional: trigger on release-2025, release-beta, etc.
    paths-ignore:
      - 'docs/**'       
      - '**/*.md'
      - '**/*.txt'    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Build
        run: echo "build"

  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Test - mozillaaa
        run: echo "test mozillaaa"

      - name: Print Test - Safari
        run: echo "test safari"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Deploy
        run: echo "deploy"
